// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "CoreMinimal.h"
#include "UObject/Interface.h"
#include "MfGameplayInterface.generated.h"

// This class does not need to be modified.
//Boilerplate stuff
UINTERFACE(MinimalAPI)
class UMfGameplayInterface : public UInterface
{
	GENERATED_BODY()
};

// Add interface functions to this class. This is the class that will be inherited to implement this interface.
class HOBBYPROJECT_API IMfGameplayInterface
{
	GENERATED_BODY()

public:

	//This function is designed to be overridden by a Blueprint, but also has a default native implementation. 
	// Declares an additional function named the same as the main function, but with _Implementation added to the end, which is where code should be written. 
	// The autogenerated code will call the _Implementation method if no Blueprint override is found.
	UFUNCTION(BlueprintNativeEvent, Category = "MF Gameplay Interface")
	void Interact(APawn* InstigatorPawn);
};
